CREATE TABLE CATEGORY (
       ID INT NOT NULL AUTO_INCREMENT
     , NAME VARCHAR(100) NOT NULL
     , UNIQUE UQ_NAME (NAME) NOT NULL
     , PRIMARY KEY (ID)
);

CREATE TABLE BOOK (
       ID INT NOT NULL AUTO_INCREMENT
     , CATEGORY_ID INT NOT NULL
     , ISBN VARCHAR(10) NOT NULL
     , TITLE VARCHAR(500) NOT NULL
     , PRICE DECIMAL(4,2) NOT NULL
     , UNIQUE UQ_BOOK (CATEGORY_ID, TITLE)
     , PRIMARY KEY (ID)
     , CONSTRAINT FK_BOOK FOREIGN KEY (CATEGORY_ID)
                  REFERENCES CATEGORY (ID)
);